// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5trjkL0PPxQxo8HPO_wVN69b4oT0H-mY',
    appId: '1:310913809655:android:3257c312e88736752ae7f2',
    messagingSenderId: '310913809655',
    projectId: 'jobportal-fba7a',
    storageBucket: 'jobportal-fba7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_59_5jYV9cnyYq7MKidm5losjzoiU9lA',
    appId: '1:310913809655:ios:5161bd246c93e3072ae7f2',
    messagingSenderId: '310913809655',
    projectId: 'jobportal-fba7a',
    storageBucket: 'jobportal-fba7a.appspot.com',
    androidClientId: '310913809655-jkpp0h1tdfar6mglahns796cf6ikgpp4.apps.googleusercontent.com',
    iosClientId: '310913809655-nfcv6og3j5uca9i8g8h0uir2tcrtntjg.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobPortal',
  );

}